// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SubPriorityApplyConfiguration represents an declarative configuration of the SubPriority type for use
// with apply.
type SubPriorityApplyConfiguration struct {
	Num *int `json:"num,omitempty"`
}

// SubPriorityApplyConfiguration constructs an declarative configuration of the SubPriority type for use with
// apply.
func SubPriority() *SubPriorityApplyConfiguration {
	return &SubPriorityApplyConfiguration{}
}

// WithNum sets the Num field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Num field is set to the value of the last call.
func (b *SubPriorityApplyConfiguration) WithNum(value int) *SubPriorityApplyConfiguration {
	b.Num = &value
	return b
}
